# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - circleci
    docker:
      # specify the version you desire here
      - image: mihirogi/openjdk8-serverless

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      # run tests!
      - run: gradle test
      - run: sls config credentials -k ${AWS_ACCESS_KEY} -s ${AWS_SECRET_KEY} -p aws
      - run: sls deploy --mail $NICONICO_MAILADDRESS --password $NICONICO_PASSWORD  --webhook $DISCORD_WEBHOOK_ENDPOINT